[package]
name = "pipico_simple_example"
version = "0.1.0"
authors = ["BenMoon <brombh@desy.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = ""
ndarray-stats = ""
noisy_float = ""
itertools = ""